apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: vinitkulkarni/database-image
        resources:
              limits:
                cpu: 500m
              requests:
                cpu: 200m
---
kind: Service
apiVersion: v1
metadata:
  name: database-service
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: database
      port: 3306
      targetPort: 3306
